import Head from 'next/head';
import Image from 'next/image';
import Navigation from '../components/Navigation';
import Footer from '../components/Footer';
import card1 from '../public/card1.png';
import card2 from '../public/card2.png';
import card3 from '../public/card3.png';
import card4 from '../public/card4.png';
import card5 from '../public/card5.png';
import grid1 from '../public/grid1.png';
import grid2 from '../public/grid2.png';
import grid3 from '../public/grid3.png';
import grid4 from '../public/grid4.png';
import grid5 from '../public/grid5.png';
import grid6 from '../public/grid6.png';
import grid7 from '../public/grid7.png';
import grid8 from '../public/grid8.png';
import grid9 from '../public/grid9.png';
import grid10 from '../public/grid10.png';

export default function Home() {
	return (
		<>
			<Head>
				<title>Create Next App</title>
				<meta name='description' content='Generated by create next app' />
				<link rel='icon' href='/favicon.ico' />
			</Head>
			<div className='intro'>
				<div className='intro-media'>
					<video
						className='intro-media-video'
						src='https://nextjs.wpengine.com/wp-content/uploads/2020/05/example-video.mp4'
						autoPlay
						muted
						loop
					></video>
				</div>
				<Navigation />

				<main className='main'>
					<center>
						<h1>Travel</h1>
					</center>
					<h4>
						&nbsp;&nbsp;&nbsp;&nbsp;Lorem ipsum dolor sit amet consectetur,
						adipisicing elit. Expedita, earum sapiente nobis ad dolores
						repudiandae eveniet. Autem sunt voluptatibus molestiae dolorem non
						voluptas laborum quos numquam, mollitia similique quam assumenda
						enim ratione atque hic commodi modi. Fugit cum maxime eaque ratione
						tempora, rem assumenda facilis fuga saepe rerum alias nobis corporis
						sed atque, neque aliquid dolor libero eum explicabo, impedit in
						reprehenderit incidunt beatae! Dignissimos aut, neque repudiandae
						dolorum culpa consectetur cumque nobis, placeat earum, eaque facere.
						Possimus officiis similique assumenda delectus error ipsum et
						dolorum dignissimos nisi dolore, rerum laboriosam, pariatur a omnis
						aut sapiente. Molestias harum nam quidem?
					</h4>
				</main>
				<card className='card-container'>
					<div className='card'>
						<div className='front'>
							<Image src={card1} width={300} height={200} />
							<div className='card-intro'>
								Labore cillum cillum aliquip culpa cupidatat fugiat magna aliqua
								fugiat. Amet pariatur irure sit reprehenderit cillum culpa
								aliqua laborum incididunt labore culpa do elit magna. Do irure
								ipsum commodo esse minim et eu irure ea proident dolor sint
								dolor tempor. Veniam non cupidatat fugiat Lorem cupidatat
								voluptate.
							</div>
						</div>
						<div className='back'>
							<Image src={card5} width={600} height={300} />
						</div>
					</div>
					<div className='card'>
						<div className='front'>
							<Image src={card2} width={300} height={200} />
							<div className='card-intro'>
								Labore cillum cillum aliquip culpa cupidatat fugiat magna aliqua
								fugiat. Amet pariatur irure sit reprehenderit cillum culpa
								aliqua laborum incididunt labore culpa do elit magna. Do irure
								ipsum commodo esse minim et eu irure ea proident dolor sint
								dolor tempor. Veniam non cupidatat fugiat Lorem cupidatat
								voluptate.
							</div>
						</div>
						<div className='back'>
							<Image src={card5} width={600} height={300} />
						</div>
					</div>
					<div className='card'>
						<div className='front'>
							<Image src={card3} width={300} height={200} />
							<div className='card-intro'>
								Labore cillum cillum aliquip culpa cupidatat fugiat magna aliqua
								fugiat. Amet pariatur irure sit reprehenderit cillum culpa
								aliqua laborum incididunt labore culpa do elit magna. Do irure
								ipsum commodo esse minim et eu irure ea proident dolor sint
								dolor tempor. Veniam non cupidatat fugiat Lorem cupidatat
								voluptate.
							</div>
						</div>
						<div className='back'>
							<Image src={card5} width={600} height={300} />
						</div>
					</div>
					<div className='card'>
						<div className='front'>
							<Image src={card4} width={300} height={200} />
							<div className='card-intro'>
								Labore cillum cillum aliquip culpa cupidatat fugiat magna aliqua
								fugiat. Amet pariatur irure sit reprehenderit cillum culpa
								aliqua laborum incididunt labore culpa do elit magna. Do irure
								ipsum commodo esse minim et eu irure ea proident dolor sint
								dolor tempor. Veniam non cupidatat fugiat Lorem cupidatat
								voluptate.
							</div>
						</div>
						<div className='back'>
							<Image src={card5} width={600} height={300} />
						</div>
					</div>
				</card>
				<div className='grid'>
					<div className='box1'>
						<Image src={grid1} />
					</div>
					<div className='box2'>
						<Image src={grid2} />
					</div>
					<div className='box3'>
						<Image src={grid3} />
					</div>
					<div className='box4'>
						<Image src={grid4} />
					</div>
					<div className='box5'>
						<Image src={grid5} />
					</div>
					<div className='box6'>
						<Image src={grid6} />
					</div>
					<div className='box7'>
						<Image src={grid7} />
					</div>
					<div className='box8'>
						<Image src={grid8} />
					</div>
					<div className='box9'>
						<Image src={grid9} />
					</div>
					<div className='box10'>
						<Image src={grid10} />
					</div>
				</div>

				<div className='epilog'></div>
			</div>
			<Footer />
		</>
	);
}
// ../Quang.mp4
